# Generated by Django 3.2.13 on 2022-07-03 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220702_0017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
